{% if cookiecutter.network_policies %}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: minio-ingress-policy
  namespace: minio-internal-{% raw %}{{ .Values.environment }}{% endraw %}
spec:
  endpointSelector:
    matchLabels:
      app: minio
  ingress:
    - fromEndpoints:
      - {}
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
{% endif %}
