apiVersion: v1
kind: Service
metadata:
  name: dlp-proxy-service
  namespace: minio-external-{% raw %}{{ .Values.environment }}{% endraw %}
  labels:
    app: dlp-nginx-proxy
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: dlp-nginx-proxy