apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager-{{ .Values.environment }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
            namespace: aws-agent-env-{{ .Values.environment }}
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
            namespace: aws-agent-env-{{ .Values.environment }}
