apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager-{{ .Values.environment }}
  namespace: training-{{ .Values.environment }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials-{{ .Values.environment }}
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials-{{ .Values.environment }}
            key: secret-access-key
