apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credentials
spec:
  secretStoreRef:
    name: shared-credentials
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: credentials-secret
    creationPolicy: Merge
    deletionPolicy: Delete
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: /apis/openai
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: /apis/anthropic      
      sourceRef:
        storeRef:
          name: shared-credentials
          kind: ClusterSecretStore
    - secretKey: AWS_CREDENTIALS
      remoteRef:
        key: /aws
