apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: localhost:5001/hello:{{ .Values.environment }}
          imagePullPolicy: Always
          args:
            - "-listen=:8081"
            - "-text=hello"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081