apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
        - name: logging-container
          image: localhost:5001/logging:{{ .Values.environment }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081