{{- if not .Values.nginx }}
{{- $_ := set .Values "nginx" dict }}
{{- end }}
{{- if not .Values.keda }}
{{- $_ := set .Values "keda" dict }}
{{- end }}

---
# Deploy Nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-app-{{ .Values.environment }}
  labels:
    app: nginx
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: nginx
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: nginx
        image: "nginx:latest"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# Nginx Service
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-app-{{ .Values.environment }}
  labels:
    app: nginx
    environment: {{ .Values.environment }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx
    environment: {{ .Values.environment }}
---
# KEDA Interceptor for HTTP requests
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: nginx-http-scaler
  namespace: nginx-app-{{ .Values.environment }}
spec:
  scaleTargetRef:
    name: nginx
    kind: Deployment
    apiVersion: apps/v1 
    service: nginx
    port: 80
  hosts:
  - {{ .Values.environment }}.example.com
  replicas:
    min: 1
    max: 10
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      targetValue: 50
