apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability-{{ .Values.environment }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55680
          http:
            endpoint: 0.0.0.0:55681

    processors:
      batch:

    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: observability-{{ .Values.environment }}
  labels:
    app: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          image: {{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.collector.ports.otlpGrpc }}
            - name: otlp-http
              containerPort: {{ .Values.collector.ports.otlpHttp }}
          resources:
            requests:
              memory: {{ .Values.collector.resources.requests.memory }}
            limits:
              memory: {{ .Values.collector.resources.limits.memory }}
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otelcol/config.yaml
              subPath: config.yaml
      volumes:
        - name: otel-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: observability-{{ .Values.environment }}
  labels:
    app: opentelemetry-collector
spec:
  ports:
    - name: otlp-grpc
      port: {{ .Values.collector.ports.otlpGrpc }}
      targetPort: {{ .Values.collector.ports.otlpGrpc }}
    - name: otlp-http
      port: {{ .Values.collector.ports.otlpHttp }}
      targetPort: {{ .Values.collector.ports.otlpHttp }}
  selector:
    app: opentelemetry-collector
