apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-alpha
  namespace: team-alpha-{% raw %}{{ .Values.environment }}{% endraw %}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-beta
  namespace: team-beta-{% raw %}{{ .Values.environment }}{% endraw %}