apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-alpha-quota
  namespace: team-alpha-{% raw %}{{ .Values.environment }}{% endraw %}
spec:
  hard:
    cpu: "8"
    memory: 16Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-beta-quota
  namespace: team-beta-{% raw %}{{ .Values.environment }}{% endraw %}
spec:
  hard:
    cpu: "8"
    memory: 16Gi
    pods: "10"