apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: feast-{{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 'bitnami/redis:latest'
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_USERNAME
              value: "feast"
            - name: REDIS_PASSWORD
              value: "feast"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: feast-{{ .Values.environment }}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis