rayClusterName: raycluster
nginx:
  enabled: true
  initialReplicas: 1
  image: "nginx:latest"
  exporterImage: "nginx/nginx-prometheus-exporter:0.10.0"

# KEDA scaling configuration
keda:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  pollingInterval: 15
  cooldownPeriod: 300
  stabilizationWindowSeconds: 300
  scaleDownPercentage: 50
  scaleDownPeriodSeconds: 60
  prometheusServerAddress: "http://prometheus.monitoring.svc.cluster.local:9090"
  requestRateThreshold: "10"  # Scale when more than 10 requests per second